import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import MainLayout from '../layouts/MainLayout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Клиника Рази</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <h1 className='display-1'>Salam</h1>
      </MainLayout>
    </>
  )
}
